name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Determine current live environment
      id: live-env
      run: |
        if pm2 list | grep -q "polyvacances0"; then echo "polyvacances0" > live-env.txt; else echo "polyvacances1" > live-env.txt; fi
        cat live-env.txt

    - name: Set deployment target
      id: target-env
      run: |
        if [ $(cat live-env.txt) == "polyvacances0" ]; then echo "polyvacances1" > target-env.txt; else echo "polyvacances0" > target-env.txt; fi
        cat target-env.txt

    - name: Move files to target environment
      run: |
        TARGET_ENV=$(cat target-env.txt)
        mv -vuf * ~/$(cat target-env.txt)
        mv -vuf .* ~/$(cat target-env.txt)

    - name: Install dependencies
      run: |
        cd ~$(cat target-env.txt)
        yarn install

    - name: Build the app
      run: |
        cd ~$(cat target-env.txt)
        yarn build

    - name: Switch traffic to the new environment
      run: |
        LIVE_ENV=$(cat live-env.txt)
        TARGET_ENV=$(cat target-env.txt)
        pm2 delete $LIVE_ENV
        pm2 start yarn --name $TARGET_ENV -- start

    - name: Cleanup old environment
      run: |
        rm -rf ~$(cat live-env.txt)/* !(.env*|node_modules)
