name: Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: yarn install
  
      - name: Generate Prisma Client
        run: yarn prisma migrate deploy
  
      - name: Build Next.js app
        run: yarn build
      
      - name: Start the app
        run: yarn start