name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Determine current live environment
      id: live-env
      run: |
        if pm2 list | grep -q "polyvacances0"; then echo "polyvacances0" > ~/polyvacances-live-env.txt; else echo "polyvacances1" > ~/polyvacances-live-env.txt; fi
        cat ~/polyvacances-live-env.txt

    - name: Set deployment target
      id: target-env
      run: |
        if [ $(cat ~/polyvacances-live-env.txt) == "polyvacances0" ]; then echo "polyvacances1" > ~/polyvacances-target-env.txt; else echo "polyvacances0" > ~/polyvacances-target-env.txt; fi
        cat ~/polyvacances-target-env.txt

    - name: Move files to target environment
      run: |
        TARGET_ENV=$(cat ~/polyvacances-target-env.txt)
        rsync -av --delete --exclude='.env*' --exclude='public/uploads' ./ ~/$(cat ~/polyvacances-target-env.txt)/

    - name: Install dependencies
      run: |
        cd ~/$(cat ~/polyvacances-target-env.txt)
        yarn install

    - name: Build the app
      run: |
        cd ~/$(cat ~/polyvacances-target-env.txt)
        yarn build

    - name: Switch traffic to the new environment
      run: |
        LIVE_ENV=$(cat ~/polyvacances-live-env.txt)
        TARGET_ENV=$(cat ~/polyvacances-target-env.txt)
        pm2 delete $LIVE_ENV
        pm2 start yarn --name $TARGET_ENV -- start

    # - name: Cleanup old environment
    #   run: |
    #     rm -rf ~$(cat ~/polyvacances-live-env.txt)/* !(.env*|public/uploads)
